version: '3'
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:password@db:27017/users-db
    depends_on:
      - db
